# fly.toml app configuration file generated for yata on 2024-11-08T16:38:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yata'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
