CREATE TABLE "tasks" (
    id SERIAL PRIMARY KEY,
    owner INT NOT NULL,
    title varchar(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
)
